version: '3'
services:

  jenkins:
    build: ./jenkins
    ports:
    - "8080:8080"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    networks:
      vn1:

  jupyter:
    build: ./data_science
    ports:
    - "8888:8888"
    networks:
      vn1:

  registry:
    image: registry:2
    ports:
    - "5000:5000"
    networks:
      vn1:

networks:
  vn1:
    driver: bridge